default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: JobChange_development

test:
  <<: *default
  database: JobChange_test

production:
  <<: *default
  database: JobChange_production
  username: JobChange
  password: <%= ENV['JOBCHANGE_DATABASE_PASSWORD'] %>
